exclude: ^(translations/|.*\.css|.*\.svg|versioneer.py|octoprint_onedrive_files/_version.py)
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-case-conflict
          - id: check-json
          - id: check-yaml
          - id: check-toml
          - id: check-merge-conflict
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: ["--py37-plus"]
            exclude: "setup.py|versioneer.py|_version.py"
    - repo: https://github.com/OctoPrint/codemods
      rev: "0.6.3"
      hooks:
          - id: codemod_batch
            args:
                ["--check", "not_in", "--check", "detect_past_builtins_imports"]
    - repo: https://github.com/PyCQA/isort
      rev: "5.11.4"
      hooks:
          - id: isort
            args: ["--profile", "black", "--filter-files"]
    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.4
      hooks:
          - id: prettier
            args: ["--tab-width", "4"]
